INSERT INTO AGENT (Matricule,PrenomAgent,NomAgent) 
	VALUES	
			("S138","Ba","Moustapha"),
			("S257","Badiane","Doudou"),
			("S126","Camara","Mouhamed"),
			("S079","Camara","Ibrahima"),
			("S33","Diatta","Attab"),
			("S76","Diop","Ibra"),
			("S31","Diouf","Assane"),
			("S135","Djignaly","Moustapha"),			
			("S165","Fall","Saer"),			
			("S98","Guèye","Mamadou"),
			("S131","Mbaye","Ameth"),
			("S052","Mbaye","Boubacar"),
			("S263","Mbaye","Talla"),
			("S262","Ndir","Abdoulaye"),
			("TDX25","Niang","Bara"),
			("S042","Ndiaye","Seydou"),
			("S265","Tambedou","Abdou Aziz"),
			("S111","Sall","Maodo Malick"),
			("S112","Thiam","Cheikh"),
			("S113","Thiaw","Abdoulaye"),
			("S114","Top","Malick"),
			("S115","Wellë","Pape Mouhamed"),
			("S116","Ndiaye","Atoumane"),
			("S117","Mbaye","Issa"),
			("S118","Sané","Arfan"),
			("S119","Sankaré","Alpha"), 
			("S120","Sarr","Abou sidiki"),
			("S121","Sarr","Abou"),
			("S1","Seck","Ibrahima"), 
			("S2","Sène","Modou"), 
			("S3", "Sow","Cheikh Tidjane"),
			("S4","Nzalé","Mouhamed"),
			("S5","Sakho","Moustapha"),
			("S6","Saleh","Nazar"); 

